PV_recruit_finder_route/PV_recruit_finder/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("search_module.urls", namespace="search_module")),
]

PV_recruit_finder_route/search_module/urls.py
from django.urls import path

from search_module.views import *

app_name = "search_module"

urlpatterns = [
    path("", index, name="index"),
    path("recruits/", recruits, name="recruits"),
    path("teams/", teams, name="teams"),
    path("guilds/", guilds, name="guilds"),
    path('auth/user/', get_authenticated_user,
         name='get_authenticated_user'),
    path('oauth2/', home, name='oauth2'),
    path('oauth2/login/', discord_login, name='oauth_login'),
    path('oauth2/login/redirect/', discord_login_redirect,
         name='discord_login_redirect')
]

PV_recruit_finder_route/search_module/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


# https://pyrewood-village.eu/


class User(AbstractUser):
    """Guild owner, who manage recruiting part
    -- also main User"""

    class Meta:
        verbose_name_plural = "Users"
        ordering = ["username"]

    def __str__(self):
        return f"{self.username}"


class InGameClass(models.Model):
    name = models.CharField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = "Classes"
        ordering = ["name"]

    def __str__(self):
        return self.name


class InGameSpec(models.Model):
    name = models.CharField(
        max_length=255, unique=True
    )  # TODO: check for Frost Holy  Protection

    class Meta:
        verbose_name_plural = "Specialisations"
        ordering = ["name"]

    def __str__(self):
        return self.name


class Character(models.Model):
    class_name = models.ForeignKey(
        InGameClass, on_delete=models.CASCADE, related_name="character_class"
    )
    spec_name = models.ForeignKey(
        InGameSpec, on_delete=models.CASCADE, related_name="character_spec"
    )

    class Meta:
        verbose_name_plural = "Characters"
        constraints = [
            models.UniqueConstraint(
                fields=["class_name", "spec_name"], name="unique_class_spec"
            ),
        ]
        ordering = ["spec_name"]

    def get_class_image(self):
        if self.class_name.name == "Death Knight":
            return "character_icons/spec_icons/death_knight/dk.jpeg"
        return f"character_icons/spec_icons/{self.class_name}/{self.class_name}.jpeg"

    def get_spec_image(self):
        if self.class_name.name == "Death Knight":
            return f"character_icons/spec_icons/death_knight/{self.spec_name.name}.jpg"
        if self.spec_name.name == "Feral DPS":
            return "character_icons/spec_icons/druid/Feral_cat.jpg"
        if self.spec_name.name == "Feral Tank":
            return "character_icons/spec_icons/druid/Feral_bear.jpg"
        if self.spec_name.name == "Beast Mastery":
            return "character_icons/spec_icons/hunter/Beast_Mastery.jpg"

        if self.spec_name.name == "Protection":
            if self.class_name.name == "Warrior":
                return "character_icons/spec_icons/warrior/Protection.jpg"
            return "character_icons/spec_icons/paladin/Protection.jpg"

        if self.spec_name.name == "Holy":
            if self.class_name.name == "Paladin":
                return "character_icons/spec_icons/paladin/Holy.jpg"
            return "character_icons/spec_icons/priest/Holy.jpg"

        return f"character_icons/spec_icons/{self.class_name.name}/{self.spec_name.name}.jpg"

    def __str__(self):
        return f"{self.spec_name} {self.class_name}"


class Recruit(models.Model):
    UPTIME_DAYS_CHOICES = [
        ("Monday", "Monday"),
        ("Tuesday", "Tuesday"),
        ("Wednesday", "Wednesday"),
        ("Thursday", "Thursday"),
        ("Friday", "Friday"),
        ("Saturday", "Saturday"),
        ("Sunday", "Sunday"),
    ]
    nickname = models.CharField(max_length=255, blank=False, null=False, unique=True)
    character = models.ForeignKey(Character, on_delete=models.SET_DEFAULT, default=None)
    note = models.CharField(max_length=255, blank=True, null=True)
    wcl = models.IntegerField(blank=True, null=True)  # TODO: WCL API sync
    uptime_days = (
        models.CharField(  # TODO: make it as foreign key to PlannedActivity or smth
            max_length=255, choices=UPTIME_DAYS_CHOICES, null=True, blank=True
        )
    )
    rt_start = models.TimeField(default=None, null=True, blank=True)
    rt_end = models.TimeField(default=None, null=True, blank=True)
    discord_tag = models.CharField(
        max_length=255, null=False, blank=True, default="unknown"
    )

    class Meta:
        verbose_name_plural = "Recruits"
        ordering = ["nickname"]

    def __str__(self):
        return f"{self.nickname}: Character: {self.character}. Note: {self.note}. WCL: {self.wcl}. Uptime: {self.uptime_days}"


class PlannedActivity(models.Model):
    RAID_DAYS_CHOICES = [
        ("Monday", "Monday"),
        ("Tuesday", "Tuesday"),
        ("Wednesday", "Wednesday"),
        ("Thursday", "Thursday"),
        ("Friday", "Friday"),
        ("Saturday", "Saturday"),
        ("Sunday", "Sunday"),
    ]
    raid_day = models.CharField(
        max_length=255,
        choices=RAID_DAYS_CHOICES,
    )
    start_time = models.TimeField()
    end_time = models.TimeField()
    by_team = models.ForeignKey(
        "Team", on_delete=models.CASCADE, null=False, blank=False, default=None
    )

    class Meta:
        verbose_name_plural = "Planned activities"
        ordering = ["by_team"]

    def __str__(self):
        return f"{self.raid_day}: {self.start_time} -> {self.end_time}"


class Team(models.Model):
    guild = models.ForeignKey(
        "Guild", on_delete=models.CASCADE, blank=False, null=False
    )
    team_name = models.CharField(
        max_length=255, default=guild.name, null=True, blank=True
    )

    team_size = models.IntegerField()
    team_progress = models.IntegerField(default=0)
    active_search = models.BooleanField(default=True)
    looking_for = models.ManyToManyField(
        Character, related_name="looking_for", blank=True, default=None
    )
    team_note = models.CharField(
        max_length=1000,
        blank=True,
        null=True,
    )

    required_active_days_amount = models.IntegerField(default=0)

    LOOT_SYSTEM_CHOICES = [
        ("Loot Council", "Loot Council"),
        ("EPGP", "EPGP"),
        ("DKP", "DKP"),
        ("SR", "SR"),
        ("BIS > MS > OS roll", "BIS > MS > OS roll"),
        ("GDKP", "GDKP"),
        ("Roll", "Roll"),
        ("Other", "Other"),
    ]

    loot_system = models.CharField(
        max_length=20,
        choices=LOOT_SYSTEM_CHOICES,
        blank=False,
        null=False,
        default="Other",
    )

    class Meta:
        verbose_name_plural = "Teams"
        ordering = ["?"]
        constraints = [
            models.UniqueConstraint(
                fields=["team_name", "guild"], name="unique_team_guild"
            ),
        ]

    def clean(self):
        if not self.team_name:
            self.team_name = self.guild.name
        if self.team_progress > self.guild.highest_progress:
            self.guild.highest_progress = self.team_progress

        self.guild.save()

    def __str__(self):
        return f"Team {self.team_name}"


class Guild(models.Model):
    """Main list object"""

    FACTION_CHOICES = [
        ("Alliance", "Alliance"),
        ("Horde", "Horde"),
    ]
    name = models.CharField(max_length=255, blank=False, null=False, unique=True)
    faction = models.CharField(
        max_length=10,
        choices=FACTION_CHOICES,
        blank=False,
        null=False,
        default="Unrecognized",
    )
    owner = models.ForeignKey(
        "User",
        on_delete=models.CASCADE,
        related_name="guild_owner",
        blank=False,
        null=False,
    )
    highest_progress = models.IntegerField(
        default=0, null=True, blank=True
    )  # team.clean

    discord_link = models.CharField(max_length=255, null=True, blank=True)
    apply_link = models.CharField(max_length=255, null=True, blank=True)
    wcl_link = models.URLField(verbose_name="wcl_link", null=True, blank=True)
    guild_note = models.CharField(max_length=1000, null=True, blank=True)
    avatar = models.CharField(max_length=255, null=True, blank=True)

    class Meta:
        verbose_name_plural = "Guilds"
        ordering = ["?"]

    def __str__(self):
        return f"{self.name}"

PV_recruit_finder_route/search_module/views.py
from django.contrib.auth import authenticate, login
from django.contrib.sites import requests
from django.http import HttpRequest, JsonResponse
from django.shortcuts import render, redirect

from .models import *

app_name = "search_module"

def index(request):
    context = {
        "num_guilds": Guild.objects.count(),
        "num_teams": Team.objects.count(),
        "num_recruits": Recruit.objects.count(),
    }
    return render(request, template_name="search_module/index.html",
                  context=context)


def recruits(request):
    context = {
        "num_recruits": Recruit.objects.count(),
        "all_recruits": Recruit.objects.all(),
    }
    return render(request, template_name="search_module/recruits.html",
                  context=context)


def teams(request):
    context = {
        "num_teams": Team.objects.count(),
        "all_teams": Team.objects.all(),
    }
    return render(request, template_name="search_module/teams.html",
                  context=context)


def guilds(request):
    context = {
        "num_guilds": Guild.objects.count(),
        "all_guilds": Guild.objects.all(),
    }
    return render(request, template_name="search_module/guilds.html",
                  context=context)


auth_url_discord = "https://discord.com/api/oauth2/authorize?client_id=1204777768374771804&response_type=code&redirect_uri=http%3A%2F%2F127.0.0.1%3A8000%2Flogin%2F&scope=identify+guilds"
def home(request: HttpRequest) -> JsonResponse:
  return JsonResponse({ "msg": "Hello World" })

def get_authenticated_user(request: HttpRequest):
    print(request.user)
    user = request.user
    return JsonResponse({
        "id": user.id,
        "discord_tag": user.discord_tag,
        "avatar": user.avatar,
        "public_flags": user.public_flags,
        "flags": user.flags,
        "locale": user.locale,
        "mfa_enabled": user.mfa_enabled
    })


def discord_login(request: HttpRequest):
    return redirect(auth_url_discord)


def discord_login_redirect(request: HttpRequest):
    code = request.GET.get('code')
    print(code)
    user = exchange_code(code)
    discord_user = authenticate(request, user=user)
    discord_user = list(discord_user).pop()
    print(discord_user)
    login(request, discord_user)
    return redirect("/auth/user")


def exchange_code(code: str):
    data = {
        "client_id": "",
        "client_secret": "",
        "grant_type": "authorization_code",
        "code": code,
        "redirect_uri": "http://localhost:8000/oauth2/login/redirect",
        "scope": "identify"
    }
    headers = {
        'Content-Type': 'application/x-www-form-urlencoded'
    }
    response = requests.post("https://discord.com/api/oauth2/token", data=data,
                             headers=headers)
    print(response)
    credentials = response.json()
    access_token = credentials['access_token']
    response = requests.get("https://discord.com/api/v6/users/@me", headers={
        'Authorization': 'Bearer %s' % access_token
    })
    print(response)
    user = response.json()
    print(user)
    return user

PV_recruit_finder_route/templates/search_module/guilds.html
{% extends 'base.html' %}
{% block unique_content %}

  <p>Currently {{ num_guilds }} <strong>guilds</strong> are looking for players:<br></p></p>

  <style>

      .bg_and_placement {
          background-color: #50221f !important;
          color: #ffffff !important;
          text-align: center;
      }


  </style>

  <table class="table">
    <thead>
    <tr>
      <th scope="col" class="bg_and_placement">Name</th>
      <th scope="col" class="bg_and_placement">Faction</th>
      <th scope="col" class="bg_and_placement">Teams</th>
      <th scope="col" class="bg_and_placement">Owner</th>
      <th scope="col" class="bg_and_placement">Highest_progress</th>
      <th scope="col" class="bg_and_placement">Discord_link</th>
      <th scope="col" class="bg_and_placement">Apply_link</th>
      <th scope="col" class="bg_and_placement">Wcl_link</th>
      <th scope="col" class="bg_and_placement">Guild_note</th>
      <th scope="col" class="bg_and_placement">Avatar</th>

    </tr>
    </thead>
    <tbody>
    {% for guild in all_guilds %}
      <tr>
        <th scope="row" class="bg_and_placement" style="text-align: left">{{ guild.name }}</th>
        <td class="bg_and_placement">{{ guild.faction }}</td>
        <td class="bg_and_placement">
          {% for team in guild.team_set.all %}
            {{ team.team_name }}
            {% if not forloop.last %}
              ,
            {% endif %}
          {% endfor %}
        </td>
        <td class="bg_and_placement">{{ guild.owner }}</td>
        <td class="bg_and_placement">{{ guild.highest_progress }}</td>
        <td class="bg_and_placement">{{ guild.discord_link }}</td>
        <td class="bg_and_placement">{{ guild.apply_link }}</td>
        <td class="bg_and_placement">{{ guild.wcl_link }}</td>
        <td class="bg_and_placement">{{ guild.guild_note }}</td>
        <td class="bg_and_placement">{{ guild.avatar }}</td>


      </tr>
    {% endfor %}
    </tbody>
  </table>

{% endblock unique_content %}

PV_recruit_finder_route/templates/search_module/index.html
{% extends 'base.html' %}

{% block unique_content %}
  <h1>Welcome to the Pyrewood Village Recruitment Hub!<br>In this place,
    guilds can strengthen their ranks,
    and players can find their new home :)</h1>
  <p><br>Contact information about <a href="recruits">players</a> is only available to  <a href="/login">authorized</a> recruiters</p>
  <p>Information about <a href="guilds">guilds</a> and their <a href="teams">teams</a> is accessible to all users<br></p>
  <p> Currently:
     <ul>
      <li>{{ num_guilds }} guilds have registered their teams</li>
      <li>{{ num_teams }} teams are looking for players</li>
      <li>{{ num_recruits }} players are looking for a team</li>
    </ul>
  </p>

{% endblock unique_content %}

PV_recruit_finder_route/templates/search_module/recruits.html
{% extends 'base.html' %}
{% load static %}
{% block unique_content %}

  <p>Currently {{ num_recruits }} <strong>players</strong> are looking for team:<br></p></p>

  <style>

      .bg_and_placement {
          background-color: #50221f !important;
          color: #ffffff !important;
          text-align: center;
      }

  </style>


  <table class="table">
    <thead>
    <tr>
      <th scope="col" class="bg_and_placement">nickname</th>
      <th scope="col" class="bg_and_placement">character</th>
      <th scope="col" class="bg_and_placement">uptime_days</th>
      <th scope="col" class="bg_and_placement">wcl</th>

      <th scope="col" class="bg_and_placement">discord</th>
      <th scope="col" class="bg_and_placement">note</th>


      <th scope="col" class="bg_and_placement">rt_start</th>
      <th scope="col" class="bg_and_placement">rt_end</th>

    </tr>
    </thead>
    <tbody>
    {% for recruit in all_recruits %}
      <tr>
        <th scope="row" class="bg_and_placement" style="text-align: left">{{ recruit.nickname }}</th>


        <td class="bg_and_placement">
          <img src="{% static recruit.character.get_class_image %}" alt="class_image">
          <img src="{% static recruit.character.get_spec_image %}" alt="spec_image">

        </td>

        <td class="bg_and_placement">{{ recruit.uptime_days }}</td>
        <td class="bg_and_placement">{{ recruit.wcl }}</td>
        <td class="bg_and_placement">{{ recruit.discord_tag }}</td>
        <td class="bg_and_placement">{{ recruit.note }}</td>

        <td class="bg_and_placement">{{ recruit.rt_start }}</td>
        <td class="bg_and_placement">{{ recruit.rt_end }}</td>

      </tr>
    {% endfor %}
    </tbody>
  </table>

{% endblock unique_content %}

PV_recruit_finder_route/templates/search_module/teams.html
{% extends 'base.html' %}
{% block unique_content %}

  <p>Currently {{ num_teams }} <strong>teams</strong> are looking for player:<br></p></p>

  <style>

      .bg_and_placement {
          background-color: #50221f !important;
          color: #ffffff !important;
          text-align: center;
      }


  </style>

  <table class="table">
    <thead>
    <tr>
      <th scope="col" class="bg_and_placement">Name</th>
      <th scope="col" class="bg_and_placement">Guild</th>
      <th scope="col" class="bg_and_placement">Size</th>
      <th scope="col" class="bg_and_placement">Progress</th>
      <th scope="col" class="bg_and_placement">Active days per week</th>
      <th scope="col" class="bg_and_placement">Loot system</th>
      <th scope="col" class="bg_and_placement">Note</th>
      <th scope="col" class="bg_and_placement">Looking for</th>
      <th scope="col" class="bg_and_placement">Active search</th>
    </tr>
    </thead>
    <tbody>
    {% for team in all_teams %}
      <tr>
        <th scope="row" class="bg_and_placement" style="text-align: left">{{ team.team_name }}</th>
        <td class="bg_and_placement">{{ team.guild }}</td>
        <td class="bg_and_placement">{{ team.team_size }}</td>
        <td class="bg_and_placement">{{ team.team_progress }}</td>
        <td class="bg_and_placement">{{ team.required_active_days_amount }}</td>
        <td class="bg_and_placement">{{ team.loot_system }}</td>
        <td class="bg_and_placement">{{ team.team_note }}</td>

        <td class="bg_and_placement">
          {% for character in team.looking_for.all %}
            {{ character }}
            {% if not forloop.last %}, {% endif %}
          {% endfor %}
        </td>


        <td class="bg_and_placement">{{ team.active_search }}</td>
      </tr>
    {% endfor %}
    </tbody>
  </table>

{% endblock unique_content %}