Lessons/library/library/urls.py
from django.contrib import admin
from django.urls import path, include
from catalog.views import *

app_name = "catalog"

urlpatterns = [
    path("__debug__/", include("debug_toolbar.urls")),
    path("", index, name="index"),
    path(
        "literary-formats/",
        LiteraryFormatListView.as_view(),
        name="literary-formats-list",
    ),
    path("books/", BookListView.as_view(), name="book-list"),
    path("books/<int:pk>/", book_detail_view(), name="book-detail"),
]

Lessons/library/catalog/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse


# Create your models here.
class LiteraryFormat(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ("name",)


class Author(AbstractUser):
    pseudonym = models.CharField(max_length=63, null=True, blank=True)

    class Meta:
        ordering = ("username",)

    def __str__(self):
        return f"{self.username}: {self.first_name} {self.last_name}"


class Book(models.Model):
    title = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    format = models.ForeignKey(
        LiteraryFormat, on_delete=models.CASCADE, related_name="books"
    )
    authors: list = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="books"
    )

    class Meta:
        ordering = ("title",)

    def get_absolute_url(self):
        return reverse("catalog:book-detail", args=[str(self.id)])

    def __str__(self):
        return f"{self.title} (price: {self.price}, format: {self.format.name})"

Lessons/library/catalog/views.py
from django.http import HttpRequest, HttpResponse, Http404
from django.shortcuts import render
from django.views import generic

from .models import *


def index(request: HttpRequest) -> HttpResponse:
    context = {
        "num_books": Book.objects.count(),
        "num_authors": Author.objects.count(),
        "num_literary_formats": LiteraryFormat.objects.count(),
        "literary_format_list": LiteraryFormat.objects.all(),
    }
    return render(request, "catalog/index.html", context=context)


# def literary_format_list_view(request: HttpRequest) -> HttpResponse:
#     literary_format_list = LiteraryFormat.objects.all()
#     context = {
#         "literary_format_list": literary_format_list
#     }
#     return render(
#         request,
#         "catalog/literary_format_list.html",
#         context=context)


class LiteraryFormatListView(generic.ListView):
    model = LiteraryFormat
    template_name = "catalog/literary_format_list.html"
    context_object_name = "literary_format_list"
    # queryset = LiteraryFormat.objects.filter(name__startswith="example")


class BookListView(generic.ListView):
    model = Book
    queryset = Book.objects.select_related(
        "format"
    )  # ORM N+1 issue fixed by select_related
    paginate_by = 10


def book_detail_view(request: HttpRequest, pk: int) -> HttpResponse:
    try:
        context = {"book": Book.objects.get(id=pk)}
    except Book.DoesNotExist:
        raise Http404("Book does not exist")
    return render(request, template_name="catalog/book_detail.html", context=context)

Lessons/library/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Library</title>
</head>
{% load static %}
<body>

{% block sidebar %}
{% include "includes/sidebar.html" %}
{% endblock sidebar %}



{% block content %}
  {% include "catalog/literary_format_list.html" %}
{% endblock content %}

{% block books %}
  {% include "catalog/book_list.html" %}
{% endblock books %}

{% block pagination %}
  {% include "includes/pagination.html" %}
{% endblock %}

</body>
</html>

Lessons/library/templates/catalog/book_detail.html
{% extends "base.html" %}
{% block content %}
  <h1>Title: {{ book.title }}</h1>>
{% endblock content %}

Lessons/library/templates/catalog/book_list.html
{% extends "base.html" %}
{% block books %}
  {% if book_list %}
    <ul>

    {% for book in book_list %}
      <li>
        {#        <a href="{% url 'catalog:book-detail' book.id %}"> {{ book.title }}</a>#}
        <a href="{{ book.get_absolute_url }}"> {{ book.title }}</a>
      </li>
    {% endfor %}
  {% else %}
    <p> no books </p>
  {% endif %}
</ul>


{% endblock %}

Lessons/library/templates/catalog/index.html
{% extends "base.html" %}
{% block index %}
  hi from index
{% endblock index %}

Lessons/library/templates/catalog/literary_format_list.html
{% extends "base.html" %}
{% block content %}


  {% if literary_format_list %}
    <ul>

  {% for lf in literary_format_list %}
    <li>{{ lf.name }}</li>
  {% endfor %}
  {% else %}
  <p>there's no lf here </p>
  {% endif %}
</ul>
{% endblock %}

Lessons/library/templates/includes/pagination.html
  {#  BOOTSTRAP paginator#}
{% if is_paginated %}
  <h1>book list</h1>

  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          prev
        </a>
      </li>
    {% endif %}
  </ul>
  {% endif %}

  {li class="page-item active">
  <span class="page-link"> {{ page_obj.number }} of {{ paginator.num_pages }}</span>
  </li>

  {#  BOOTSTRAP paginator#}
  {% if is_paginated %}
  <ul class="pagination">
  {% if page_obj.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.next_page_number }}">
        prev
      </a>
    </li>
  </ul>
  {% endif %}
  {% endif %}

Lessons/library/templates/includes/sidebar.html
{% block sidebar %}
{#catalog:literary-format-list#}
<ul>
  <li><a href="#">Sidebar#1</a></li>
  <li><a href="#">Sidebar#2</a></li>
  <li><a href="#">Sidebar#3</a></li>
</ul>

{% endblock sidebar %}